apiVersion: v1
kind: ConfigMap
metadata:
  name: plugin
data:
  plugin.yaml: |
    apiVersion: argoproj.io/v1alpha1
    kind: ConfigManagementPlugin
    metadata:
      name: cmp-plugin
    spec:
      generate:
        command: [sh, -c]
        args:
          - |
            for file in ../../../base/*.yaml; do 
            ytt -f "$file" -f values.yaml
            done
      discover:
        fileName: "**/values.yaml"

   #>/tmp/tmp.yaml && mv /tmp/tmp.yaml "$(basename "$file")"; 

apiVersion: v1
kind: ConfigMap
metadata:
  name: cmp-ytt
  namespace: argocd-ppd
data:
# ytt command could be changed to fit your repository structure
  plugin.yaml: |
    apiVersion: argoproj.io/v1alpha1
    kind: ConfigManagementPlugin
    metadata:
      name: cmp-yttfile
    spec:
      version: v1.0
      init:
        command: [sh, -c, 'echo "Initializing..."']
      generate:
        command: [sh, -c]
        args: ["ytt -f values.yaml -f /base "] 
      discover:
        fileName: "values.yaml"